In [23]:
import numpy as np
neuron = 4

In [24]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [25]:
def sigmoid_derivative(x):
    return x * (1.0 - x)

In [26]:
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        print('inputs \n', self.input)
        print()
        self.weights1 = np.random.rand(self.input.shape[1], neuron)
        print('weights1 \n', self.weights1)
        print()
        self.weights2 = np.random.rand(neuron, 1)
        print('weights2 \n', self.weights2)
        print()
        self.y = y
        print('y \n', self.y)
        print()
        self.output = np.zeros(self.y.shape)
        print('output \n', self.output)
        print()

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        #print('layer1 \n', self.layer1)
        #print()
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        #print('output \n', self.output)
        #print()

    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y-self.output)*sigmoid_derivative(self.output)))

        d_weights1 = np.dot(self.input.T,(np.dot(2*(self.y-self.output)*sigmoid_derivative(self.output),self.weights2.T)*sigmoid_derivative(self.layer1)))

        self.weights1 += d_weights1
        self.weights2 += d_weights2


In [27]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

In [28]:
nn = NeuralNetwork(X, y)

inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.05536023 0.8231724  0.89497374 0.79147608]
 [0.51655806 0.00687156 0.13180264 0.32595663]
 [0.17834756 0.30345457 0.89634865 0.22100689]]

weights2 
 [[0.97505625]
 [0.13684611]
 [0.69651034]
 [0.78103614]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]



In [32]:
for i in range(100):
    nn.feedforward()
    nn.backprop()

print(nn.output)

[[0.05784711]
 [0.88311301]
 [0.87074125]
 [0.15061934]]
