# Numpy 1 العمليات الرياضية

In [2]:
from numpy import * # بنستدعي المكتبه بهذا الشكل وده معناه استدعيلي كل الدوال الخاصه بيها

a = sin(30)
b = cos(30)
c = tan(30)

# هلاقي ارقام غريبه طلعت لان مشكلة الدوال المثلثيه انها بتتعامل بال radians وليس ال degree
# عشان نحل المشكله دي نضرب في => pi/180
print(a, b, c)


-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [3]:
a = sin(30*pi/180)
b = cos(30*pi/180)
c = tan(30*pi/180)
# كدا هتطلع الارقام دقيقه
print(a)
print(b)
print(c)


0.49999999999999994
0.8660254037844387
0.5773502691896257


In [5]:
from numpy import *
# ممكن احول الرقم الي degree بطريقه تاني 

a = sin(deg2rad(30))
b = cos(deg2rad(30))
c = tan(deg2rad(30))

print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [6]:
from numpy import *

# round التقريب أمر

a = round(3.685228)
b = round(3.685228,1)
c = round(3.685228,2)
d = round(3.685228,3)
e = round(3.685228,4)

print(a)
print(b)
print(c)
print(d)
print(e)

4
3.7
3.69
3.685
3.6852


In [8]:
# ceil امر التقريب لاعلي
# floor امر التقريب لأقل

a = ceil(3.685228)
b = floor(3.685228)

print(a)
print(b)

4.0
3.0


In [9]:
# mod امر باقي القسمه 
# power امر الأس

a = mod(20, 7)
b = power(2, 5)

print(a)
print(b)

6
32


# Numpy 2 كتابة المصفوفات

In [11]:
from numpy import *
# يتم استخدام أمر array لتحويل ليست الي مصفوفه

a = [2,3,4,5,6,7,8]
b = array(a)

print(a) # output => list
print(b) # output => matrix

[2, 3, 4, 5, 6, 7, 8]
[2 3 4 5 6 7 8]


In [12]:
# ويمكن عمل مصفوفة ثنائية الابعاد

a = [[1,2,3],[5,3,6],[9,6,5]] # لازم تكون الارقام متساويه ف كل ليست يعني العدد قد بعض عشان اعمل مصفوفه
b = array(a)
# => كدا هعمل مصفوفه ثنائة الابعاد 

print(a)
print(b)

[[1, 2, 3], [5, 3, 6], [9, 6, 5]]
[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [17]:
# وممكن استخدام أمر range لعمل مصفوفة

a = array([range(i, i+3) for i in [2, 4, 6]])

print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [18]:
# يمكن عمل تعريف للمتغيرات بعد كتابتها

a = array([('x',3,4.2),('y',4,5.3),('z',5,6.3)],
          dtype = [('name', 'U5'), ('number','i2'),
                   ('value', 'f4')])

print(a)

[('x', 3, 4.2) ('y', 4, 5.3) ('z', 5, 6.3)]


In [21]:
from numpy import *
# باستخدام امر empty يمكن عمل مصفوفة فارغة

a = empty((3,2)) # كدا هيعملي مصفوفه فاضيه قيمتها اصفار ابعادها 3 في 2

print(a)


[[6.36598737e-314 1.06099790e-313]
 [1.06099790e-313 1.48539705e-313]
 [1.48539705e-313 1.90979621e-313]]


In [22]:
from numpy import *

# أمر uniform يأتي بقيمة عشوائية

a = random.uniform(1, 10) # => دي معناها هتلي رقم واحد عشوائي يكون بين 1 الي 10 

b = random.uniform(1, 10, 20) # => دي معناها هتلي 20 رقم عشوائي قيمتهم من 1 الي 10 

print(a)
print("-"*20)
print(b)

4.007274151687811
--------------------
[5.9338957  3.47436047 2.60366716 8.75172331 1.50970857 9.39496395
 3.22691445 6.45735862 5.3745684  2.98937801 1.104582   5.49217135
 6.11936909 9.96159005 6.24589924 7.35612958 6.11962958 8.45746031
 4.56057097 4.02479359]


In [23]:
# بأمر random.random يمكن عمل مصفوفه بارقام عشوائيه بين 0 الي 1

a = random.random((2,3))

print(a)

[[0.67244339 0.55897822 0.67025869]
 [0.8645219  0.1971904  0.24968542]]


In [24]:
# أمر random.normal ياتي بالتوزيع الطبيعي لارقام بين ال 0 وال 1 عدد 10 ارقام

a =random.normal(0,1,10)

print(a)

[-1.12228728 -1.14701091 -1.71545856  0.26315137 -0.56880463  0.48026268
  0.3439699   1.10761018 -1.15267455  0.4728313 ]


In [37]:
# بأمر random.randint يمكن تحديد رقم عشوائي صحيح من 0 الي الرقم المحدد

a = random.randint(150) # كدا هيجيب رقم عشوائي واحد فقط

b = random.randint(5, size=6) # كدا هيجيب 6 ارقام عشوائيه من 0 الي 5

c =random.randint(5,20, size=5) # => كدا هيجيب ليا 5 ارقام عشوائيه من 5 الي 20

# => ويمكن عمل مصفوفة ارقام صحيحة بين ارقام محدده

d = random.randint(0,10, (3,3)) # كدا اعملي ماتركيس ارقامها من 0 الي 10 وتكون 3 في 3

e = random.randint(5, 12, size=(3, 4, 5)) # => كدا يعني اعملي 3 مصفوفات كل مصفوفه تكون 4 في 5

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

55
--------------------
[0 3 0 2 2 2]
--------------------
[10 11  7  5 15]
--------------------
[[4 1 8]
 [7 3 5]
 [1 4 6]]
--------------------
[[[ 6  9  7 11  5]
  [11  9  5  7 11]
  [ 7 11  8 11 10]
  [ 7 10 11  8 11]]

 [[ 7  7 10  6  8]
  [ 6  6  8  9 10]
  [ 5  7 10 11  6]
  [ 9  5  7  9 11]]

 [[ 8 11  7  5  6]
  [ 7  9  6 11  9]
  [ 8 11  6  9 10]
  [ 9  5 11  7 10]]]


In [38]:
a = random.randint(1, 60, 25) # => هتلي 25 رقم قيمتهم تتراوح بين 1 الي 59
b = reshape(a,(5,5)) # => دي معناها اعملي للارقام دي تشكيل يعني اعملهملي مصفوفة لو كانت الاعداد متناسبة

print(a)
print(b)

[22  4 34 11 49 13 55 19 51 49 59 49 38 51 15 24 50 41 51 35 51 43 16 28
 57]
[[22  4 34 11 49]
 [13 55 19 51 49]
 [59 49 38 51 15]
 [24 50 41 51 35]
 [51 43 16 28 57]]


# Numpy 3 كتابة المصفوفات

In [42]:
from numpy import *

a = random.rand(15) # هنا يعمل ارقام عشوائيه من 0 لي 1 بالعدد المطلوب
print(a)

print("-"*20)

b = random.rand(5,3) # كدا هيعمل مصفوفه ابعادها 5 في 3
print(b)

print("-"*20)

c = random.rand(5, 3,2) # كدا اعملي مصفوفه فيها 5 طبقات ابعادها 3 في 2
print(c)


[0.90039635 0.46307108 0.52129978 0.84176903 0.71514521 0.46263866
 0.76565102 0.65590828 0.50243866 0.54797128 0.61860231 0.34594954
 0.20488569 0.29652256 0.58918056]
--------------------
[[0.20300173 0.38417639 0.52912591]
 [0.72385455 0.48538094 0.36547555]
 [0.31497733 0.23295172 0.62065618]
 [0.39934134 0.42223954 0.59602157]
 [0.72955771 0.29873702 0.03094178]]
--------------------
[[[0.74210082 0.70041148]
  [0.098012   0.97924163]
  [0.87875191 0.11975247]]

 [[0.58610976 0.56151584]
  [0.03585    0.34370197]
  [0.17133505 0.72498998]]

 [[0.21233639 0.91787397]
  [0.51330479 0.04145691]
  [0.42872655 0.82222066]]

 [[0.45065934 0.31216953]
  [0.28632783 0.60836353]
  [0.56838275 0.96123608]]

 [[0.71616293 0.28261025]
  [0.79025108 0.22233525]
  [0.1894312  0.84291301]]]


In [46]:
# أمر choice يختار قيمة عشوائيه 

y = [1,2,3,4,5,6,7,8,9]

a = random.choice(y)
print(a)

print("-"*20)

random.shuffle(y) # => أمر shuffle بيعمل ترتيب عشوائي للقيم بيخلطهم
print(y)

1
--------------------
[3, 4, 9, 5, 7, 8, 1, 2, 6]


In [47]:
# عمل مصفوفة كلها 0 او 1 

a = zeros((3,3))
b = ones((3,3))

print(a)
print("-"*20)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
# مصفوفة الوحدة 
a = eye(5) # كدا هيعملي مصفوفة كلها اصفار ماعدا القطر الرئيسي للمصفوفه يكون بي 1

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
# أمر full بيعمل مصفوفة بنفس الرقم المعطي

a = full((3,5), 35)

print(a)

[[35 35 35 35 35]
 [35 35 35 35 35]
 [35 35 35 35 35]]


In [51]:
# ممكن كتابة مصفوفة بأبعاد محددة 

a = arange(18).reshape(3,6)
b = arange(27).reshape(3,3,3)

c = arange(18)

print(a)
print("-"*20)
print(b)

print("-"*20)

random.shuffle(c)

d = c.reshape(3,6)

print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[11 17  9  1 14 12]
 [ 6  7 15  3  4 10]
 [16 13  2  5  0  8]]


In [54]:
# لكتابة أرقام متوزعه بالتساوي بين رقمين 

a = linspace(0, 30) # => الميثود دي لو محددتش عايز كام رقم بيجيب لوحده 50 رقم 
# كدا هيجبلي 50 رقم قيمتهم من 0 الي 30

b = linspace(0,100,5) # => كدا هيجبلي 5 ارقام قيمتهم بين 0 الي 100

print(a)
print("-"*20)
print(b)
print("-"*20)


# ممكن احولها لمصفوفة 

c = linspace(0,30, 12).reshape(3,4)
d = linspace(0,100,27).reshape(3,3,3)

print(c)
print("-"*20)
print(d)

[ 0.          0.6122449   1.2244898   1.83673469  2.44897959  3.06122449
  3.67346939  4.28571429  4.89795918  5.51020408  6.12244898  6.73469388
  7.34693878  7.95918367  8.57142857  9.18367347  9.79591837 10.40816327
 11.02040816 11.63265306 12.24489796 12.85714286 13.46938776 14.08163265
 14.69387755 15.30612245 15.91836735 16.53061224 17.14285714 17.75510204
 18.36734694 18.97959184 19.59183673 20.20408163 20.81632653 21.42857143
 22.04081633 22.65306122 23.26530612 23.87755102 24.48979592 25.10204082
 25.71428571 26.32653061 26.93877551 27.55102041 28.16326531 28.7755102
 29.3877551  30.        ]
--------------------
[  0.  25.  50.  75. 100.]
--------------------
[[ 0.          2.72727273  5.45454545  8.18181818]
 [10.90909091 13.63636364 16.36363636 19.09090909]
 [21.81818182 24.54545455 27.27272727 30.        ]]
--------------------
[[[  0.           3.84615385   7.69230769]
  [ 11.53846154  15.38461538  19.23076923]
  [ 23.07692308  26.92307692  30.76923077]]

 [[ 34.61538462 

In [56]:
# المصفوفة القطرية 

a = diag(array([5,12,4,-1,3])) # المصفوفة كلها هتكون اصفار ماعدا القطر الرئيسي هيكون الارقام اللي محددها دي
b = diag(array([5,12,4,-1,3]),k=3)

print(a)
print("-"*20)
print(b)


[[ 5  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  3]]
--------------------
[[ 0  0  0  5  0  0  0  0]
 [ 0  0  0  0 12  0  0  0]
 [ 0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


# Numpy 4 التعامل مع المصفوفات

In [2]:
from numpy import *
# ممكن حساب الارقام التي ليست صفر

a = random.randint(0,10, (3,3))

b = count_nonzero(a) # => كدا هيحسب عدد الارقام التي لا تساوي صفر
print(a)
print(b)
print("-"*20)

# => لو عاوز احسب عدد ارقام معينه 

c = count_nonzero(a>5) # => كدا معانها احسب عدد الارقام اللي اكبر من 5
d = count_nonzero(a<8) # => كدا معناها احسب عدد الارقام اللي اقل من 8
print(a)
print(c)
print(d)


[[8 5 5]
 [9 0 0]
 [4 1 0]]
6
--------------------
[[8 5 5]
 [9 0 0]
 [4 1 0]]
2
7


In [3]:
# وممكن حساب الارقام يكون بالصف كله 

a = random.randint(0,10, (3,3))
b = count_nonzero(a>5, axis=1)
c = count_nonzero(a<8, axis=1)

print(a)
print(b)
print(c)

[[6 5 9]
 [0 9 9]
 [1 0 1]]
[2 2 0]
[2 1 3]


In [5]:
# لمعرفة هل في رقم اكبر او اصغر من كذا ولا لا 

a = random.randint(0,10, (3,3))

b = any(a>5) # => كدا هيشوف هل في رقم اكبر من 5 ولا لا وهيديني ترو او فلوس

print(a)
print(b)
print("-"*20)
#=========================================================================

# => ويمكن عملها في كل صف 

c = any(a > 5 , axis=1)
print(c)

[[8 1 7]
 [5 6 2]
 [4 3 7]]
True
--------------------
[ True  True  True]


In [7]:
# ويمكن معرفة هل كل العناصر شرط معين 

a = random.randint(0,10, (3,3))

b = all(a>5) # كدا لو كانت كل القيم اكبر من 5 هيبقي true 

print(a)
print(b)
print("-"*20)

c = all(a<10) # كدا هيشوف هل كل القيم اقل من 10
print(c)

[[9 6 7]
 [3 4 6]
 [6 5 1]]
False
--------------------
True


In [8]:
# => ويمكن معرفة هل العناصر اكبر من او اصغر من رقم معين 

a = random.randint(5,20, size=9).reshape(3,3)

b = a>10 # => دا هيجيب لي الترو والفولس في مصفوفة 
c = a<15 # => دا هيجيب لي الترو والفولس في مصفوفة 
d = a[b] # => دي معناها هيجيب القيم الخاصه بالترو والفولس
e = a[c] # => دي معناها هيجيب القيم الخاصه بالترو والفولس

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

[[ 9 19 11]
 [16  5  7]
 [19  8 14]]
--------------------
[[False  True  True]
 [ True False False]
 [ True False  True]]
--------------------
[[ True False  True]
 [False  True  True]
 [False  True  True]]
--------------------
[19 11 16 19 14]
--------------------
[ 9 11  5  7  8 14]


In [9]:
# => مقارنة المصفوفات 

a = arange(9).reshape(3,3)
b = arange(9).reshape(3,3)

c = 2*b # هيبقي فيه مضاعفات المصفوفة

d = isclose(a,b, rtol=0.1) # => ادتله قيمتين مصفوفتين وهيقارن بينهم لو كل قيمه بينها 0.1 كدا هيكون ترو 
e = isclose(a,c, rtol=0.1)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
--------------------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
--------------------
[[ True False False]
 [False False False]
 [False False False]]
--------------------


In [11]:
# => يمكن ضرب قيم المصفوفة في بعضها (ضرب الدوت )

a = arange(5)
b = empty(5)

multiply(a, 10, out=b) # => كدا يعني خد قيم a واضربهم في 10
# وبعدين الناتج ضيفهم في المصفوفة الفارغه b 

print(a)
print(b)
print("-"*20)
#===========================================

#=> لرفع كل العناصر لأس معين 

power(a,4, out=b)
print(a)
print(b)


[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]
--------------------
[0 1 2 3 4]
[  0.   1.  16.  81. 256.]


# Numpy 5 التعامل مع المصفوفات 

In [14]:
from numpy import *
# => مجموع قيم المصفوفة 

a = arange(15)

b = add.reduce(a) # => كدا هيجبلي مجموع قيم المصفوفة

print(a)
print(b)
print("-"*20)
#===========================================

c = arange(2, 8)

d = multiply.reduce(c) #=> كدا هيضرب القيم في بعض

print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105
--------------------
[2 3 4 5 6 7]
5040


In [15]:
# => عملية ضرب متبادلة 

a = arange(2,8)

b = multiply.outer(a,a)

print(a)
print(b)

[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


In [17]:
# => جمع كل الارقام السابقه

a = arange(10)

b = add.accumulate(a)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


In [18]:
# => ضرب الارقام السابقه 

a = arange(2,8)

b = multiply.accumulate(a)

print(a)
print(b)

[2 3 4 5 6 7]
[   2    6   24  120  720 5040]


In [19]:
# => لمعرفة عدد عناصر المصفوفة او عدد صفوفها لو اكتر من بعد

a = arange(12)
b = len(a)

c = a.reshape(3,4)
d = len(c)

print(a)
print(b)
print("-"*20)

print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3


In [20]:
# => لمعرفة كل عدد عناصرها 

a = arange(12)
b = a.size

c = a.reshape(3,4)
d = c.size

print(a)
print(b)
print("-"*20)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


In [21]:
# => لمعرفة عدد الابعاد بالتفصيل 

a = arange(12)
b = a.shape

c = a.reshape(3,4)
d = c.shape

print(a)
print(b)
print("-"*20)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [22]:
# => عدد ابعادها 

a = arange(12)
b = a.ndim

c = a.reshape(3,4)
d = c.ndim

print(a)
print(b)
print("-"*20)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
--------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [23]:
# => نوع البيانات في المصفوفة 

a = array(['a','b','c','d','e'])
b = a.dtype

c = arange(12)
d = c.reshape(3,4)
e = d.dtype

print(a)
print(b)
print("-"*20)

print(c)
print(d)
print(e)

['a' 'b' 'c' 'd' 'e']
<U1
--------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int32


# Numpy 6 التعامل مع المصفوفات

In [24]:
from numpy import *
# => وممكن نعمل تشكيل للمصفوفة بالطريقة دي 

a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {}; {} {} {}'.format(1,2,3,4,5,6))

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


In [25]:
# => نجمع قيم المحور هكذا 

a = arange(9)
b = a.reshape(3,3)
c = trace(b)

print(b)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [27]:
# => قيمة المصفوفة وقيمة ايجان فاليو

a = arange(9)
b = a.reshape(3,3)
c = linalg.det(b) # => هيجيب ليا قيمة المصفوفة
d = linalg.eig(b) # => هيجيب ليا قيمة ايجان فاليو

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
0.0
EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -1.15433316e-15]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [28]:
# => الاقتطاع من المصفوفة

a = arange(10)

b = a[3] # => هتلي العنصر رقم 3
c = a[3:9] # => يعني هتلي القيم من 3 الي 9-1
d = a[3:9:2] # => هتلي القيم من 3 ال 9-1 وتسكيب خطوتين 
e = a[-1] # => هات اخر رقم
f = a[-3] # => هات العنصر رقم 3 من جهة اليمين

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


[0 1 2 3 4 5 6 7 8 9]
3
[3 4 5 6 7 8]
[3 5 7]
9
7


In [30]:
# => الاقتطاع من المصفوفة لو ليها ابعاد

a = arange(36).reshape(6,6)

b = a[3] # => كدا هيجبلي الصف كامل 
c = a[3:9]
d = a[3:9:2]
e = a[-1]
f = a[-3]

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)
print(f)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--------------------
[18 19 20 21 22 23]
--------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
--------------------
[30 31 32 33 34 35]
--------------------
[18 19 20 21 22 23]


In [31]:
# => اقتطاع باتسخدام , 

a = arange(36).reshape(6,6)

b = a[3,1] # => كدا هتلي العنصر اللي اتقاطع بين الصف رقم 4 والعمود التاني 
c = a[3,:]
d = a[:,2]
e = a[:,1:3]
f = a[1:2,:]

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)
print(f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--------------------
19
--------------------
[18 19 20 21 22 23]
--------------------
[ 2  8 14 20 26 32]
--------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
--------------------
[[ 6  7  8  9 10 11]]


# Numpy 7 التعامل مع المصفوفات

In [2]:
from numpy import *
# => اقتطاع باتسخدام , 

a = arange(36).reshape(6,6)

b = a[3:4,1:5]
c = a[2:,3:]
d = a[:2,:3]
e = a[:,-1]
f = a[-1,:]

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)
print(f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--------------------
[[19 20 21 22]]
--------------------
[[15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
--------------------
[[0 1 2]
 [6 7 8]]
--------------------
[ 5 11 17 23 29 35]
--------------------
[30 31 32 33 34 35]


In [3]:
a = arange(36).reshape(6,6)

b = a[::2,::3]
c = a[::-1,::-1]
d = a[:2:-1,:3:-1]
e = a[2::2,3::3]
f = a[-1::,-1::]

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)
print(f)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
--------------------
[[ 0  3]
 [12 15]
 [24 27]]
--------------------
[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
--------------------
[[35 34]
 [29 28]
 [23 22]]
--------------------
[[15]
 [27]]
--------------------
[[35]]


In [8]:
# تعديل القيم 

a = arange(16).reshape(4,4)
print(a)

a[2,3] = 0
print(a)
a[:,3] = 0
print(a)
a[2,:] = 0
print(a)
a[:,:] = 0
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10  0]
 [12 13 14 15]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 8  9 10  0]
 [12 13 14  0]]
[[ 0  1  2  0]
 [ 4  5  6  0]
 [ 0  0  0  0]
 [12 13 14  0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
# النسخه المربوطه

a = arange(16).reshape(4,4)
print(a)
b = a[:,1:3]
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [10]:
# النسخه المستقلة

a = arange(16).reshape(4,4)
print(a)
b = a[:,1:3].copy()
print(b)
a[:,:] = 5
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [11]:
# ثلاثة ابعاد 

a = arange(18).reshape(3,3,2)

c = a[1]
d = a[1,2]
e = a[2,2,1]

print(a)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
--------------------
[[ 6  7]
 [ 8  9]
 [10 11]]
--------------------
[10 11]
--------------------
17


In [17]:
# التجزيء

x = [11,22,33,44,55,66,77,88]
print(x)
print("-"*20)
x1,x2,x3 = split(x, (3,6))
print(x1,x2,x3)
print("-"*20)
x1,x2,x3 = split(x, (1,5))
print(x1,x2,x3)
print("-"*20)
x1,x2,x3 = split(x, (6,3))
print(x1,x2,x3)
print("-"*20)
x1,x2,x3 = split(x, (0,3))
print(x1,x2,x3)
print("-"*20)
x1,x2,x3 = split(x, (4,0))
print(x1,x2,x3)

[11, 22, 33, 44, 55, 66, 77, 88]
--------------------
[11 22 33] [44 55 66] [77 88]
--------------------
[11] [22 33 44 55] [66 77 88]
--------------------
[11 22 33 44 55 66] [] [44 55 66 77 88]
--------------------
[] [11 22 33] [44 55 66 77 88]
--------------------
[11 22 33 44] [] [11 22 33 44 55 66 77 88]


In [18]:
# تحديد عنصر

a = arange(16).reshape(4,4)

b = a[2][1]

print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
9


In [22]:
# ضم المصفوفات رأسي
# لازم يكون عدد الاعمده متساوي في كلا المصفوفات

a = arange(4).reshape(2,2)
b = 2*arange(4).reshape(2,2)

c = vstack((a,b))

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[0 1]
 [2 3]]
--------------------
[[0 2]
 [4 6]]
--------------------
[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [23]:
# ضم المصفوفات أفقي
# لازم يكون عدد الصفوف متساوي في كلا المصفوفات

a = arange(4).reshape(2,2)
b = 2*arange(4).reshape(2,2)

c = hstack((a,b))

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[0 1]
 [2 3]]
--------------------
[[0 2]
 [4 6]]
--------------------
[[0 1 0 2]
 [2 3 4 6]]


In [24]:
# زيادة رأسيه 

a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b], axis = 0) # axis = 0 => كدا زياده رأسيه

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[10 16  6]
 [17  7 18]
 [12 18 11]]
--------------------
[[19 19 12]
 [ 9  9 19]
 [11 15 15]]
--------------------
[[10 16  6]
 [17  7 18]
 [12 18 11]
 [19 19 12]
 [ 9  9 19]
 [11 15 15]]


In [25]:
# زيادة أفقيه

a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)
c = concatenate([a,b], axis = 1) # axis = 1 => كدا زياده أفقيه

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[12 11 10]
 [14  5 11]
 [ 9  9  9]]
--------------------
[[ 6  6  6]
 [13 14  8]
 [ 5  5 14]]
--------------------
[[12 11 10  6  6  6]
 [14  5 11 13 14  8]
 [ 9  9  9  5  5 14]]


In [28]:
# أكبر واصغر قيمه 
import numpy as np

a = np.random.randint(5,20, size=9).reshape(3,3)

b = np.max(a)
c = np.min(a)
d = np.argmax(a)
e = np.argmin(a)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)
print("-"*20)



[[ 7 13 10]
 [18 14  6]
 [16 15 10]]
--------------------
18
--------------------
6
--------------------
3
--------------------
5
--------------------


In [29]:
# ايجاد ال Variance وال Covariance 

a = random.randint(5,20, size=9).reshape(3,3)

b = var(a)
c = cov(a)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[ 8 12 17]
 [15  5  5]
 [15 15  9]]
--------------------
18.839506172839506
--------------------
[[ 20.33333333 -21.66666667 -14.        ]
 [-21.66666667  33.33333333  10.        ]
 [-14.          10.          12.        ]]


# Numpy 8 العمليات الرياضيه للمصفوفات

In [1]:
# الجمع والطرح 

from numpy import *

a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)

c = a+b # => جمع 
d = a-b # => طرح

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)

[[10  8  5]
 [13 19 11]
 [14  7  7]]
--------------------
[[ 6 17 16]
 [13 15 14]
 [12  8 16]]
--------------------
[[16 25 21]
 [26 34 25]
 [26 15 23]]
--------------------
[[  4  -9 -11]
 [  0   4  -3]
 [  2  -1  -9]]


In [2]:
# الضرب والقسمه 

a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)

# a*b => النوع الاول من الضرب كل رقم في اخوه

c = a*b
d = a/b # Division

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)


[[14  5 18]
 [16 15  6]
 [17 11 14]]
--------------------
[[16 12 16]
 [ 5  5 13]
 [13 13 17]]
--------------------
[[224  60 288]
 [ 80  75  78]
 [221 143 238]]
--------------------
[[0.875      0.41666667 1.125     ]
 [3.2        3.         0.46153846]
 [1.30769231 0.84615385 0.82352941]]


In [3]:
a = random.randint(5,20, size=9).reshape(3,3)
b = random.randint(5,20, size=9).reshape(3,3)

# a*n => دا معناه امسك كل رقمه اضربه في n


c = a*3
d = b/5 # Division

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)

[[14 18 19]
 [13 13  5]
 [ 5  7 17]]
--------------------
[[ 7 18 10]
 [ 9 16 15]
 [15 17  7]]
--------------------
[[42 54 57]
 [39 39 15]
 [15 21 51]]
--------------------
[[1.4 3.6 2. ]
 [1.8 3.2 3. ]
 [3.  3.4 1.4]]


In [4]:
# Multiplication Matrices

a = random.randint(1,4, size=9).reshape(3,3)
b = random.randint(1,4, size=9).reshape(3,3)

c = dot(a,b) # الضرب الجبري للمصفوفات

# لازم عدد الاعمده ف المصفوفه الاولي يساوي عدد الصفوف ف المصفوفه الثانيه

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[2 2 2]
 [1 1 2]
 [2 1 2]]
--------------------
[[1 3 3]
 [2 2 1]
 [3 1 1]]
--------------------
[[12 12 10]
 [ 9  7  6]
 [10 10  9]]


In [6]:
# Sum Values

a = random.randint(5,20, size=9).reshape(3,3)

b = sum(a) # => كدا بجيب مجموع المصفوفه
c = a.sum() # => كدا برضو بجيب مجموع المصفوفه

d = a.sum(axis=1) # => كدا هيجيب مجموع كل صف لوحده ويخليهم ف ماتريكس
e = a.sum(axis=0) # => كدا هيجيب مجموع كل عمود لوحده ويخليهم ف ماتريكس

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

[[ 6  7 15]
 [13  8 16]
 [17 16 12]]
--------------------
110
--------------------
110
--------------------
[28 37 45]
--------------------
[36 31 43]


In [7]:
# قيم احصائيه

a = random.randint(5,20, size=9).reshape(3,3)

b = a.mean() # => كدا هجيب المتوسط بتاع المصفوفه 
c = a.std() 
d = a.var() # => الانحراف

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)

[[16 18 14]
 [17 10  5]
 [ 7 11  8]]
--------------------
11.777777777777779
--------------------
4.416579314300398
--------------------
19.506172839506174
--------------------


In [8]:
# معامل الارتباط

a = random.randint(5,20, size=9).reshape(3,3)

b = corrcoef(a)

print(a)
print("-"*20)
print(b)

[[ 8 15  5]
 [10  7 10]
 [16 18 11]]
--------------------
[[ 1.         -0.95632472  0.89178333]
 [-0.95632472  1.         -0.72057669]
 [ 0.89178333 -0.72057669  1.        ]]


In [9]:
# الترتيب الأفقي والرأسي 

a = random.randint(5,20, size=9).reshape(3,3)

b = sort(a, axis=1) # كدا هيرتب كل صف أفقي
c = sort(a, axis=0) # كدا هيرتب كل صف رأسي

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)


[[10 10 15]
 [14 10 19]
 [ 6  8 10]]
--------------------
[[10 10 15]
 [10 14 19]
 [ 6  8 10]]
--------------------
[[ 6  8 10]
 [10 10 15]
 [14 10 19]]


In [3]:
# معكوس المصفوفه

a = random.randint(1,5, size=9).reshape(3,3)

b = linalg.inv(a)

c = dot(a,b)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)

[[1 3 1]
 [3 1 1]
 [1 2 1]]
--------------------
[[ 5.00000000e-01  5.00000000e-01 -1.00000000e+00]
 [ 1.00000000e+00  2.08166817e-17 -1.00000000e+00]
 [-2.50000000e+00 -5.00000000e-01  4.00000000e+00]]
--------------------
[[1.00000000e+00 1.11022302e-16 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


# Numpy 9 قراءة الملفات

In [15]:
# فتح الملفات

from numpy import *

fname = r"D:\pythonfiels\1.txt.txt"

dtype1 = dtype([('gender', '|S1'), ('height', 'f8')])

a = loadtxt(fname, dtype=dtype1, skiprows=9, usecols=(1,3))

print(a)

[(b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64) (b'M', 1.63)
 (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 ) (b'M', 1.97)
 (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]


# Numpy 10 التعامل مع كثيرة الحدود (Polynomials)

In [2]:
# الدرجه الاولي 
import numpy as np

Polynomial = np.polynomial.Polynomial

X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])

points,state = Polynomial.fit(X,Y,1,full=True)
# fit => معناها يلائم 
# num 1 in linear معناه درجه اولي 


print(points)

5.5 - 4.5 x


In [4]:
# الدرجه التانيه
import numpy as np

Polynomial = np.polynomial.Polynomial

X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])

points,state = Polynomial.fit(X,Y,2,full=True)
# fit => معناها يلائم 
# num 2 in linear معناه درجه تانيه 


print(points)

5.5 - 4.5 x - (1.62206443e-15) x**2


In [5]:
# الدرجه التالته
import numpy as np

Polynomial = np.polynomial.Polynomial

X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])

points,state = Polynomial.fit(X,Y,3,full=True)
# fit => معناها يلائم 
# num 3 in linear معناه درجه اولي 


print(points)

5.5 - 4.5 x - (1.62206443e-15) x**2 - (8.72975182e-16) x**3


In [8]:
# كتابة ال poly

a = poly1d((-7))
b = poly1d((-7,2))
c = poly1d((-7,2,1))
d = poly1d((-7,2,1,3))
e = poly1d((-7,2,1,3,6))

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

 
-7
--------------------
 
-7 x + 2
--------------------
    2
-7 x + 2 x + 1
--------------------
    3     2
-7 x + 2 x + 1 x + 3
--------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


In [9]:
# ممكن اعوض بقيمة x معينه ف المعادله 

a = poly1d((-7,2,1,3,6))

b=a(5) # كدا يعني بدل كل x حط قيمة 5 
c =a(0)
d =a(-15)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)

    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
--------------------
-4079
--------------------
6
--------------------
-360939


In [10]:
# ممكن اعوض مباشر في متغير واحد اديله درجة المعادله وقيمة التعويض 

a = polyval((1,2),2) # كدا معادله من الدرجه الاولي وهيعوض بقيمة 2 
b = polyval((1,2,3),7)
c = polyval((1,2,3,5),-3)
d = polyval((1,2,3,5,-6),12.6)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)

4
--------------------
66
--------------------
-13
--------------------
29738.769599999992


In [11]:
# اشتقاق المعادله 

a = polyder(poly1d((1,2,3))) # دي معناها اشتقلي المعادله الخطيه دي 
b = polyder(poly1d((1,2,3)),2) # دي معناها اعمل اشتقاق تراكمي يعني اشتق المعادله مرتين
c = polyder(poly1d((1,2,3)),3) # 3 

d = polyder(poly1d((1,2,3,5,12)))
e = polyder(poly1d((1,2,3,5,12)),3)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

 
2 x + 2
--------------------
 
2
--------------------
 
0
--------------------
   3     2
4 x + 6 x + 6 x + 5
--------------------
 
24 x + 12


In [12]:
# ممكن اعمل تعويض ف الاشتقاق نفسه 

a = polyder(poly1d((1,2,3)))
b = polyder(poly1d((1,2,3)),2)
c = polyder(poly1d((1,2,3)),3)

d = polyder(poly1d((1,2,3,5,12)))
e = polyder(poly1d((1,2,3,5,12)),3)

print(a(2))
print("-"*20)
print(b(0))
print("-"*20)
print(c(3))
print("-"*20)
print(d(-1))
print("-"*20)
print(e(5))

6
--------------------
2
--------------------
0
--------------------
1
--------------------
132


In [13]:
# التكامل 

a = polyint(poly1d((1,2,3)))
b = polyint(poly1d((1,2,3)),2)
c = polyint(poly1d((1,2,3)),3)


d = polyint(poly1d((1,2,3,15,12)))
e = polyint(poly1d((1,2,3,15,12)),3)

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

        3     2
0.3333 x + 1 x + 3 x
--------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
--------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
--------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 7.5 x + 12 x
--------------------
          7           6        5         4     3
0.004762 x + 0.01667 x + 0.05 x + 0.625 x + 2 x


In [14]:
# ممكن اعوض ف التكامل 

a = polyint(poly1d((1,2,3)))
b = polyint(poly1d((1,2,3)),2)
c = polyint(poly1d((1,2,3)),3)


d = polyint(poly1d((1,2,3,15,12)))
e = polyint(poly1d((1,2,3,15,12)),3)

print(a(2))
print("-"*20)
print(b(0))
print("-"*20)
print(c(3))
print("-"*20)
print(d(-1))
print("-"*20)
print(e(5))

12.666666666666666
--------------------
0.0
--------------------
24.300000000000004
--------------------
-5.2
--------------------
1429.3154761904761


In [15]:
# جذور المعادله (حلها)

# => يعني ايه قيم x اللي هتصفر المعادله 


a = roots(poly1d((1,2)))
b = roots(poly1d((1,2,3)))
c = roots(poly1d((1,2,3,5)))
d = roots(poly1d((1,2,3,5,12)))
e = roots(poly1d((1,2,3,5,12,22)))

print(a)
print("-"*20)
print(b)
print("-"*20)
print(c)
print("-"*20)
print(d)
print("-"*20)
print(e)

[-2.]
--------------------
[-1.+1.41421356j -1.-1.41421356j]
--------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
--------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
--------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]


In [16]:
# توافق النقاط 

x = array([3,6,2,5,4])
y = array([2,3,-9,6,2.5])

z = polyfit(x,y,2)

print(x)
print('-'*20)
print(y)
print('-'*20)
print(z)
print('-'*20)

[3 6 2 5 4]
--------------------
[ 2.   3.  -9.   6.   2.5]
--------------------
[ -1.78571429  17.08571429 -35.3       ]
--------------------


# Numpy 11 التعامل مع التاريخ

In [2]:
from numpy import *

x = array('2024-07-07',dtype=datetime64)

d = datetime64('2024-07-07') # ممكن بالطريقه دي كمان 

print(x)
print('-'*20)
print(d)

2024-07-07
--------------------
2024-07-07


In [3]:
x = datetime64('2024-07-25')

y = x + arange(12)

print(x)
print('-'*20)
print(y)

2024-07-25
--------------------
['2024-07-25' '2024-07-26' '2024-07-27' '2024-07-28' '2024-07-29'
 '2024-07-30' '2024-07-31' '2024-08-01' '2024-08-02' '2024-08-03'
 '2024-08-04' '2024-08-05']


In [4]:
x = datetime64('2024-07-25')

y = x - arange(12)

print(x)
print('-'*20)
print(y)

2024-07-25
--------------------
['2024-07-25' '2024-07-24' '2024-07-23' '2024-07-22' '2024-07-21'
 '2024-07-20' '2024-07-19' '2024-07-18' '2024-07-17' '2024-07-16'
 '2024-07-15' '2024-07-14']


In [5]:
x = datetime64('2002-06-01')
y = datetime64('2024-07-12')

z = y - x

print(x)
print('-'*20)
print(y)
print('-'*20)
print(z)


2002-06-01
--------------------
2024-07-12
--------------------
8077 days


# الدوال في Numpy

In [7]:
# يتم استخدامها بأداة fromfunction

x = fromfunction(lambda i : i**3, (10,))

print(x)
print('-'*20)

[  0.   1.   8.  27.  64. 125. 216. 343. 512. 729.]
--------------------


In [8]:
x = fromfunction(lambda i : 3 * (i+5)**3, (10,))

print(x)
print('-'*20)

[ 375.  648. 1029. 1536. 2187. 3000. 3993. 5184. 6591. 8232.]
--------------------


In [9]:
x = fromfunction(lambda i,j : i+j, (4,5))

print(x)
print('-'*20)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]]
--------------------


In [10]:
x = fromfunction(lambda i,j : 3*i*j, (4,5))

print(x)
print('-'*20)

[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  6. 12. 18. 24.]
 [ 0.  9. 18. 27. 36.]]
--------------------


In [11]:
x = fromfunction(lambda i,j,k : i+j+k, (2,3,4))

print(x)
print('-'*20)

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]]
--------------------


In [12]:
def powers(i):
    i = i**2
    return i

x = fromfunction(powers, (9,), dtype=int)

print(x)
print('-'*20)

[ 0  1  4  9 16 25 36 49 64]
--------------------


In [13]:
m,n = 20,5

def f(i):
    return (i % n == 0)

x = fromfunction(f, (m,), dtype=int)

print(x)
print('-'*20)

[ True False False False False  True False False False False  True False
 False False False  True False False False False]
--------------------


# The End