<h1 style="text-align: center; font-size: 38px">  Python NumPy for Linear Algebra </h1>  <br>


In [1]:
import numpy as np

In [3]:
lst1 = [1,2,3]

In [4]:
v1 = np.array(lst1)

In [5]:
v2 = np.array([2,5,7])

In [6]:
v1.shape

(3,)

In [7]:
v2.shape

(3,)

In [8]:
v1@v2

33

In [9]:
v1.dot(v2)

33

In [10]:
np.dot(v1,v2)

33

In [11]:
np.linalg.norm(v1)

3.7416573867739413

In [13]:
np.linalg.norm(v1, 1)

6.0

In [14]:
np.linalg.norm(v1,2)

3.7416573867739413

In [15]:
np.linalg.norm(v1,3)

3.3019272488946263

In [16]:
np.linalg.norm(v1, np.inf) # اكبر قيمه 

3.0

In [17]:
arr = np.array([[1,3],
                [6,7],
                [5,4]])

In [18]:
arr

array([[1, 3],
       [6, 7],
       [5, 4]])

In [19]:
v1@arr

array([28, 29])

In [20]:
v1

array([1, 2, 3])

In [21]:
arr.shape

(3, 2)

In [22]:
v3 = v1.reshape((3,1))

In [23]:
v3

array([[1],
       [2],
       [3]])

In [24]:
v3.shape

(3, 1)

In [26]:
v3.T@arr

array([[28, 29]])

In [27]:
arr_sq = arr @ arr.T

In [28]:
import sympy as sm

In [29]:
arr_sq

array([[10, 27, 17],
       [27, 85, 58],
       [17, 58, 41]])

In [30]:
M = sm.Matrix(arr_sq)

In [31]:
M

Matrix([
[10, 27, 17],
[27, 85, 58],
[17, 58, 41]])

In [32]:
M.rref()

(Matrix([
 [1, 0, -1],
 [0, 1,  1],
 [0, 0,  0]]),
 (0, 1))

In [33]:
arr_sq

array([[10, 27, 17],
       [27, 85, 58],
       [17, 58, 41]])

In [36]:
arr_sq.sum(axis=0) # هيجمع رأسي 

array([ 54, 170, 116])

In [37]:
arr_sq.sum(axis=1) # هيجمع أفقي

array([ 54, 170, 116])